name: either
description: Simple & Lightweight Error Handling Solution | Influenced by  Either in Functional Programming Languages
version: 0.0.1
repository: https://github.com/topperspal/either.git

environment:
  sdk: ">=2.12.0 <3.0.0"
